import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-woodsmoke-950`}>
        {children}
        <div className="top-0 -left-32 absolute h-32 w-1/2 bg-woodsmoke-900 blur-[250px] opacity-50" />
      </body>
    </html>
  );
}
